AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamda

  Sample SAM Template for lamda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 120
    MemorySize: 256

Resources:
  PeopleApi:
    Type: AWS::Serverless::Api
    Properties:
        Name: PeopleApi
        StageName: Dev
#  People
  CreatePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CRUD_PERSON/create/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Events:
        CreatePerson:
          Type: Api
          Properties:
            RestApiId: !Ref PeopleApi
            Path: /people
            Method: POST


Outputs:
  PeopleApi:
    Description: "API Gateway endpoint URL for Prod stage for PeopleApi"
    Value: !Sub "https://${PeopleApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/"