AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lamda

  Sample SAM Template for lamda

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
  Function:
    Timeout: 25
    MemorySize: 128

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'

  PeopleApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: PeopleApi
      StageName: Dev


  #  People
  ReadPersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CRUD_PERSON/read_one/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreatePerson:
          Type: Api
          Properties:
            RestApiId: !Ref PeopleApi
            Path: /people/{id}
            Method: GET

  UpdatePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: CRUD_PERSON/update/
      Handler: app.lambda_handler
      Runtime: python3.12
      Architectures:
        - x86_64
      Role: !GetAtt LambdaExecutionRole.Arn
      Events:
        CreatePerson:
          Type: Api
          Properties:
            RestApiId: !Ref PeopleApi
            Path: /people/
            Method: PUT

Outputs:
  PeopleApi:
    Description: "API Gateway endpoint URL for Prod stage for PeopleApi"
    Value: !Sub "https://${PeopleApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/people/"
  UpdatePersonFunction:
    Description: "Update Person Lambda Function ARN"
    Value: !GetAtt UpdatePersonFunction.Arn