name: CHECK AND DEPLOY

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  test:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    if: github.ref == 'refs/heads/master'
    name: Deploy to AWS
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Convert requirements.txt to UTF-8
        run: |
          iconv -f utf-16le -t utf-8 ./CRUD_PERSON/create/requirements.txt -o ./CRUD_PERSON/create/requirements.txt


      - name: install dependencies crud_person
        run: |
          if [ -f CRUD_PERSON/create/requirements.txt ]; then pip install -r CRUD_PERSON/create/requirements.txt; fi

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Install SAM CLI
        run: |
          pip install aws-sam-cli

      - name: Build and Deploy
        env:
          SAM_CLI_TELEMETRY: 0
        run: |
          sam build
          sam deploy --stack-name lamda --capabilities CAPABILITY_IAM --no-confirm-changeset --no-fail-on-empty-changeset